# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79166f85734cda117f80ac6cefe7e279592c6c991557398b6f3b8410637b176ccd8b109723a95a9ec5327a322cb1b19d689a086ce7a7067ae0a9f092874f20e8

test:
  secret_key_base: 86b686b88e687ad0b05ab43c186e8317db1c19fc99ca5bfb3ddc96f020a54f8e83df817f31e48afc1bd0773ff1525e10f4d42a6d2dada6709bc12b720265ee01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
